# Generated by Django 2.2.19 on 2021-02-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
